### ISSUE TITLE
Add site purpose/description

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.io#71]
Folks coming to the site without knowing anything about it are a bit confused. I'd love to add the following copy in a header (or similar) on the home page.

> Find Ruby on Rails developers looking for freelance, contract, and full-time work.

The tricky bit here is that the layout/design of the page needs to change to incorporate this. I'm open to mockups and PRs on this one and could use some help!

### To-do

- [x] Redesign homepage to add description
- [x] Mobile redesign of homepage + menu
 - [x] `Developers#show`
- [x] Devise forms (sign in, registration, passwords, confirmation, etc.)
- [x] Flash message
- [x] Footer with links to open source repo, analytics, and creators (for now)

**Comment by joemasilotti** [comment]
Work is being done in #73, but here's some progress screenshots!

<img width="1597" alt="image" src="https://user-images.githubusercontent.com/2092156/141182022-6141f038-3b84-4017-a478-99f83a142c3f.png">
<img width="401" alt="image" src="https://user-images.githubusercontent.com/2092156/141182060-88f4df4d-bea7-4bd3-bdb6-13b4f3e833e3.png">

**Comment by joemasilotti** [comment]
And we're live!

![Uploading image.png…]()
